import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar/Navbar";
import { Toaster } from "@/components/ui/sonner"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});
//kuy
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Check",
  description: "Generated by create next app",
  keywords: ["Check", "Next.js", "React", "TypeScript", "Firebase", "Tailwind CSS"],
  icons: {
    icon: [
      { url: "/Logo.svg", type: "image/svg+xml", sizes: "any" },
    ],
    apple: "/Logo.svg",
    shortcut: "/Logo.svg",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    // อยากใ้ห้อะไรอยู่ทุกหน้าเอาฟังชั่นมาใส่ตรงนี้ เช่น Navbar
  
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
        <Navbar/>
        {children}
        <Toaster position="top-center"/>
        
      </body>
    </html>

  );
}
